### ISSUE TITLE
NEWDB 

### ISSUE THREAD

**Issue by saidhfm** [dogoncouch/ldsi#10] opened 2019-01-23 05:06 UTC
(myenv) sai@sai-VirtualBox:/opt/LogESP$ make newdb
--- Loading initial migrations...
python manage.py migrate
  File "manage.py", line 14
    ) from exc
         ^
SyntaxError: invalid syntax
Makefile:90: recipe for target 'newdb-setup' failed
make: *** [newdb-setup] Error 1

**Comment by dogoncouch** [comment] 2019-02-01 03:31
It seems your environment is using python2 as the default python. I get the same error trying anything with manage.py in python2:

```
(env) root@logesp-srv:/opt/LogESP# python manage.py makemigrations
No changes detected
(env) root@logesp-srv:/opt/LogESP# python2 manage.py makemigrations
  File "manage.py", line 14
    ) from exc
         ^
SyntaxError: invalid syntax
```

Is your virtual env made with python 2 or python 3? Also, is the python binary you are using the one from your virtual env?

```
(env) root@logesp-srv:/opt/LogESP# type -p python
/opt/LogESP/env/bin/python
```

**Comment by dogoncouch** [comment] 2019-02-02 01:51
LogESP only works with python3, so check which version of python your virtual env is using:

```
python --version
```

If it's 2, you'll need to create a new virtual env with python3:

```
python3 -m venv TARGETDIR
```

**Comment by dogoncouch** [comment] 2019-02-23 18:56
Closing this issue, as it seems it is definitely caused by the virtualenv having the wrong python environment.

**Closed as completed by dogoncouch** 2019-02-23 18:56 UTC
